~/.config/hypr/themed.conf :: hyprctl reload
general {
  gaps_in = {{ spacing }}
  gaps_out = {{ spacing }}

  border_size = {{ thickness:strip }}
  col.active_border = rgb({{ accent:strip }})
  col.inactive_border = rgb({{ bg:strip }})
}

decoration {
  rounding = {{ rounding }}
  active_opacity = {{ opacity.active }}
  inactive_opacity = {{ opacity.inactive }}
}
