source = ~/.config/hypr/themed.conf

animations {
    enabled = true

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global, 1, 1, default
    animation = windows, 1, 1, default, slide
    animation = layers, 1, 1, default, slide
    animation = fade, 1, 1, default
    animation = border, 0, 1, default
    animation = borderangle, 0, 1, default
    animation = workspaces, 1, 1, default
    animation = zoomFactor, 1, 1, default
    animation = monitorAdded, 1, 1, default

}

general {
    resize_on_border = false
    allow_tearing = false

    layout = dwindle
}

dwindle {
    preserve_split = true
}

decoration {
    rounding_power = 2
}
