general {
  gaps_in = 8
  gaps_out = 8

  border_size = 2
  col.active_border = rgb(458588)
  col.inactive_border = rgb(282828)
}

decoration {
  rounding = 20
  active_opacity = 1
  inactive_opacity = 1
}
